name: Build and Package Java Web Application

on:
    push:
      branches:
        - master
      paths:
        - 'src/**'
        - 'Dockerfile'
        - 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin' # Specify the JDK distribution

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t djoksa4/kubernetes-cicd-webapp:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull existing image (if it exists)
        run: |
            docker pull your-dockerhub-username/kubernetes-cicd-webapp:latest || true
  
      - name: Tag and push old image
        run: |
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            docker tag your-dockerhub-username/kubernetes-cicd-webapp:latest your-dockerhub-username/kubernetes-cicd-webapp:$TIMESTAMP
            docker push your-dockerhub-username/kubernetes-cicd-webapp:$TIMESTAMP
  
      - name: Build Docker image
        run: docker build -t your-dockerhub-username/kubernetes-cicd-webapp:latest .
  
      - name: Push new Docker image
        run: docker push your-dockerhub-username/kubernetes-cicd-webapp:latest